import type { Theme } from "./types";

/**
 * Built-in themes. Palettes are taken from each project's own source rather
 * than eyeballed, so the hexes are the upstream ones — Kanagawa's in
 * particular come straight from `kanagawa.nvim/lua/kanagawa/colors.lua`, with
 * surfaces mapped the way that theme maps its own (`bg`, `bg_p1`, `bg_p2`).
 */
export const PRESET_THEMES: Theme[] = [
  {
    id: "light",
    name: "Light",
    dark: false,
    colors: {
      canvas: "#ffffff",
      surface: "#ffffff",
      surfaceAlt: "#f1f0ff",
      text: "#1b1b1f",
      textMuted: "#8a8a90",
      accent: "#6965db",
      accentText: "#ffffff",
      danger: "#db6965",
      stroke: "#1e1e1e",
      fill: "transparent",
    },
  },
  {
    id: "dark",
    name: "Dark",
    dark: true,
    colors: {
      canvas: "#121212",
      surface: "#1e1e1e",
      surfaceAlt: "#2e2e2e",
      text: "#e3e3e3",
      textMuted: "#8a8a8a",
      accent: "#a8a5ff",
      accentText: "#121212",
      danger: "#ff8a85",
      stroke: "#e3e3e3",
      fill: "transparent",
    },
  },
  {
    id: "nord",
    name: "Nord",
    dark: true,
    colors: {
      canvas: "#2e3440",
      surface: "#3b4252",
      surfaceAlt: "#4c566a",
      text: "#eceff4",
      textMuted: "#7b88a1",
      accent: "#88c0d0",
      accentText: "#2e3440",
      danger: "#bf616a",
      stroke: "#d8dee9",
      fill: "transparent",
    },
  },
  {
    id: "dracula",
    name: "Dracula",
    dark: true,
    colors: {
      canvas: "#282a36",
      surface: "#343746",
      surfaceAlt: "#44475a",
      text: "#f8f8f2",
      textMuted: "#6272a4",
      accent: "#bd93f9",
      accentText: "#282a36",
      danger: "#ff5555",
      stroke: "#f8f8f2",
      fill: "transparent",
    },
  },
  {
    id: "gruvbox-dark",
    name: "Gruvbox Dark",
    dark: true,
    colors: {
      canvas: "#282828",
      surface: "#3c3836",
      surfaceAlt: "#504945",
      text: "#ebdbb2",
      textMuted: "#928374",
      accent: "#fabd2f",
      accentText: "#282828",
      danger: "#fb4934",
      stroke: "#ebdbb2",
      fill: "transparent",
    },
  },
  {
    id: "solarized-light",
    name: "Solarized Light",
    dark: false,
    colors: {
      canvas: "#fdf6e3",
      surface: "#eee8d5",
      surfaceAlt: "#e0dac0",
      text: "#586e75",
      textMuted: "#93a1a1",
      accent: "#268bd2",
      accentText: "#fdf6e3",
      danger: "#dc322f",
      stroke: "#586e75",
      fill: "transparent",
    },
  },
  {
    id: "solarized-dark",
    name: "Solarized Dark",
    dark: true,
    colors: {
      canvas: "#002b36",
      surface: "#073642",
      surfaceAlt: "#10505f",
      text: "#93a1a1",
      textMuted: "#586e75",
      accent: "#268bd2",
      accentText: "#002b36",
      danger: "#dc322f",
      stroke: "#93a1a1",
      fill: "transparent",
    },
  },
  {
    id: "catppuccin-mocha",
    name: "Catppuccin Mocha",
    dark: true,
    colors: {
      canvas: "#1e1e2e",
      surface: "#313244",
      surfaceAlt: "#45475a",
      text: "#cdd6f4",
      textMuted: "#6c7086",
      accent: "#cba6f7",
      accentText: "#1e1e2e",
      danger: "#f38ba8",
      stroke: "#cdd6f4",
      fill: "transparent",
    },
  },
  {
    // sumiInk3 / sumiInk4 / sumiInk5, fujiWhite, fujiGray, crystalBlue, samuraiRed
    id: "kanagawa-wave",
    name: "Kanagawa Wave",
    dark: true,
    colors: {
      canvas: "#1F1F28",
      surface: "#2A2A37",
      surfaceAlt: "#363646",
      text: "#DCD7BA",
      textMuted: "#727169",
      accent: "#7E9CD8",
      accentText: "#1F1F28",
      danger: "#E82424",
      stroke: "#DCD7BA",
      fill: "transparent",
    },
  },
  {
    // lotusWhite3 / lotusWhite4 / lotusWhite5, lotusInk1, lotusGray2, lotusBlue4, lotusRed3
    id: "kanagawa-lotus",
    name: "Kanagawa Lotus",
    dark: false,
    colors: {
      canvas: "#f2ecbc",
      surface: "#e7dba0",
      surfaceAlt: "#e4d794",
      text: "#545464",
      textMuted: "#716e61",
      accent: "#4d699b",
      accentText: "#f2ecbc",
      danger: "#e82424",
      stroke: "#545464",
      fill: "transparent",
    },
  },
];

/** Used when settings name a theme that no longer exists. */
export const FALLBACK_THEME_ID = "light";
